# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_b2_b_extranet_match_consumer_details_service import ManaV2B2BExtranetMatchConsumerDetailsService

class TestManaV2B2BExtranetMatchConsumerDetailsService(unittest.TestCase):
    """ManaV2B2BExtranetMatchConsumerDetailsService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2B2BExtranetMatchConsumerDetailsService:
        """Test ManaV2B2BExtranetMatchConsumerDetailsService
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2B2BExtranetMatchConsumerDetailsService`
        """
        model = ManaV2B2BExtranetMatchConsumerDetailsService()
        if include_optional:
            return ManaV2B2BExtranetMatchConsumerDetailsService(
                company_name = 'example string',
                contact_email = [
                    'example string'
                    ],
                description = 'example string',
                id = 1234567891011,
                service_name = 'example string'
            )
        else:
            return ManaV2B2BExtranetMatchConsumerDetailsService(
        )
        """

    def testManaV2B2BExtranetMatchConsumerDetailsService(self):
        """Test ManaV2B2BExtranetMatchConsumerDetailsService"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
