# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_extranet_nat_translation_centralized import ManaV2ExtranetNatTranslationCentralized

class TestManaV2ExtranetNatTranslationCentralized(unittest.TestCase):
    """ManaV2ExtranetNatTranslationCentralized unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2ExtranetNatTranslationCentralized:
        """Test ManaV2ExtranetNatTranslationCentralized
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2ExtranetNatTranslationCentralized`
        """
        model = ManaV2ExtranetNatTranslationCentralized()
        if include_optional:
            return ManaV2ExtranetNatTranslationCentralized(
                prefixes = {
                    'key' : graphiant_sdk.models.mana_v2_extranet_nat_translation_device_prefixes.manaV2ExtranetNatTranslationDevicePrefixes()
                    }
            )
        else:
            return ManaV2ExtranetNatTranslationCentralized(
        )
        """

    def testManaV2ExtranetNatTranslationCentralized(self):
        """Test ManaV2ExtranetNatTranslationCentralized"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
