# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranet_b2b_matches_pause_put_response import V1ExtranetB2bMatchesPausePutResponse

class TestV1ExtranetB2bMatchesPausePutResponse(unittest.TestCase):
    """V1ExtranetB2bMatchesPausePutResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetB2bMatchesPausePutResponse:
        """Test V1ExtranetB2bMatchesPausePutResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetB2bMatchesPausePutResponse`
        """
        model = V1ExtranetB2bMatchesPausePutResponse()
        if include_optional:
            return V1ExtranetB2bMatchesPausePutResponse(
                status = 'ENUM_VALUE'
            )
        else:
            return V1ExtranetB2bMatchesPausePutResponse(
        )
        """

    def testV1ExtranetB2bMatchesPausePutResponse(self):
        """Test V1ExtranetB2bMatchesPausePutResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
