# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_extranet_service_customer_match_summary import ManaV2ExtranetServiceCustomerMatchSummary

class TestManaV2ExtranetServiceCustomerMatchSummary(unittest.TestCase):
    """ManaV2ExtranetServiceCustomerMatchSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2ExtranetServiceCustomerMatchSummary:
        """Test ManaV2ExtranetServiceCustomerMatchSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2ExtranetServiceCustomerMatchSummary`
        """
        model = ManaV2ExtranetServiceCustomerMatchSummary()
        if include_optional:
            return ManaV2ExtranetServiceCustomerMatchSummary(
                id = 1234567891011,
                lan_segment = 1234567891011,
                matched_customers = 123,
                name = 'example string',
                service_type = 'ENUM_VALUE',
                status = 'ENUM_VALUE',
                updated_at = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, )
            )
        else:
            return ManaV2ExtranetServiceCustomerMatchSummary(
        )
        """

    def testManaV2ExtranetServiceCustomerMatchSummary(self):
        """Test ManaV2ExtranetServiceCustomerMatchSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
