# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_extranet_service_policy_response import ManaV2ExtranetServicePolicyResponse

class TestManaV2ExtranetServicePolicyResponse(unittest.TestCase):
    """ManaV2ExtranetServicePolicyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2ExtranetServicePolicyResponse:
        """Test ManaV2ExtranetServicePolicyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2ExtranetServicePolicyResponse`
        """
        model = ManaV2ExtranetServicePolicyResponse()
        if include_optional:
            return ManaV2ExtranetServicePolicyResponse(
                policy = graphiant_sdk.models.mana_v2_extranet_service_producer_policy.manaV2ExtranetServiceProducerPolicy(
                    description = 'example string', 
                    global_object_device_summaries = {
                        'key' : graphiant_sdk.models.mana_v2_global_object_service_summaries.manaV2GlobalObjectServiceSummaries(
                            routing_policies = [
                                graphiant_sdk.models.mana_v2_global_object_summary.manaV2GlobalObjectSummary(
                                    attach_point = 'ENUM_VALUE', 
                                    id = 1234567891011, 
                                    ip_version = 123, 
                                    name = 'example string', 
                                    num_attached_devices = 123, 
                                    num_attached_sites = 123, 
                                    num_failures = 123, 
                                    num_in_sync_devices = 123, 
                                    num_override_devices = 123, 
                                    num_policies = 123, 
                                    num_prefixes = 123, 
                                    num_rules = 123, 
                                    num_statements = 123, 
                                    traffic_policy_type = 'ENUM_VALUE', )
                                ], )
                        }, 
                    global_object_ops = {
                        'key' : graphiant_sdk.models.mana_v2_global_object_service_ops.manaV2GlobalObjectServiceOps(
                            routing_policy_ops = {
                                'key' : 'ENUM_VALUE'
                                }, )
                        }, 
                    nat_translation_mode = graphiant_sdk.models.mana_v2_extranet_nat_translation_mode.manaV2ExtranetNatTranslationMode(
                        centralized = graphiant_sdk.models.mana_v2_extranet_nat_translation_centralized.manaV2ExtranetNatTranslationCentralized(
                            prefixes = {
                                'key' : graphiant_sdk.models.mana_v2_extranet_nat_translation_device_prefixes.manaV2ExtranetNatTranslationDevicePrefixes()
                                }, ), 
                        decentralized = graphiant_sdk.models.mana_v2_extranet_nat_translation_decentralized.manaV2ExtranetNatTranslationDecentralized(), 
                        peer_to_peer = graphiant_sdk.models.mana_v2_extranet_nat_translation_peer_to_peer.manaV2ExtranetNatTranslationPeerToPeer(), ), 
                    prefix_tags = [
                        graphiant_sdk.models.mana_v2_b2b_extranet_prefix_tag.manaV2B2bExtranetPrefixTag(
                            prefix = '10.1.2.0/24', 
                            tag = 'example string', )
                        ], 
                    service_lan_segment = 1234567891011, 
                    sites = [
                        graphiant_sdk.models.mana_v2_b2b_site_information.manaV2B2bSiteInformation(
                            bw_allocation_site_lists = 123, 
                            bw_allocation_sites = 123, 
                            policer_site_lists = graphiant_sdk.models.mana_v2_policer.manaV2Policer(
                                burst_size = 123, 
                                bw = 123, ), 
                            policer_sites = graphiant_sdk.models.mana_v2_policer.manaV2Policer(
                                burst_size = 123, 
                                bw = 123, ), 
                            site_lists = [
                                1234567891011
                                ], )
                        ], ),
                service_name = 'example string',
                service_type = 'ENUM_VALUE'
            )
        else:
            return ManaV2ExtranetServicePolicyResponse(
        )
        """

    def testManaV2ExtranetServicePolicyResponse(self):
        """Test ManaV2ExtranetServicePolicyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
