# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranet_b2b_customers_id_details_get_response import V1ExtranetB2bCustomersIdDetailsGetResponse

class TestV1ExtranetB2bCustomersIdDetailsGetResponse(unittest.TestCase):
    """V1ExtranetB2bCustomersIdDetailsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetB2bCustomersIdDetailsGetResponse:
        """Test V1ExtranetB2bCustomersIdDetailsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetB2bCustomersIdDetailsGetResponse`
        """
        model = V1ExtranetB2bCustomersIdDetailsGetResponse()
        if include_optional:
            return V1ExtranetB2bCustomersIdDetailsGetResponse(
                admin_emails = [
                    'example string'
                    ],
                name = 'example string',
                num_sites = 123,
                status = 'ENUM_VALUE',
                type = 'ENUM_VALUE'
            )
        else:
            return V1ExtranetB2bCustomersIdDetailsGetResponse(
        )
        """

    def testV1ExtranetB2bCustomersIdDetailsGetResponse(self):
        """Test V1ExtranetB2bCustomersIdDetailsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
