# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranet_b2b_customers_id_put_response import V1ExtranetB2bCustomersIdPutResponse

class TestV1ExtranetB2bCustomersIdPutResponse(unittest.TestCase):
    """V1ExtranetB2bCustomersIdPutResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetB2bCustomersIdPutResponse:
        """Test V1ExtranetB2bCustomersIdPutResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetB2bCustomersIdPutResponse`
        """
        model = V1ExtranetB2bCustomersIdPutResponse()
        if include_optional:
            return V1ExtranetB2bCustomersIdPutResponse(
                invite = graphiant_sdk.models.mana_v2_extranet_service_customer_invite.manaV2ExtranetServiceCustomerInvite(
                    admin_emails = [
                        'example string'
                        ], 
                    maximum_number_of_sites = 123, )
            )
        else:
            return V1ExtranetB2bCustomersIdPutResponse(
        )
        """

    def testV1ExtranetB2bCustomersIdPutResponse(self):
        """Test V1ExtranetB2bCustomersIdPutResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
