# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_extranet_nat_translation_peer_to_peer import ManaV2ExtranetNatTranslationPeerToPeer

class TestManaV2ExtranetNatTranslationPeerToPeer(unittest.TestCase):
    """ManaV2ExtranetNatTranslationPeerToPeer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2ExtranetNatTranslationPeerToPeer:
        """Test ManaV2ExtranetNatTranslationPeerToPeer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2ExtranetNatTranslationPeerToPeer`
        """
        model = ManaV2ExtranetNatTranslationPeerToPeer()
        if include_optional:
            return ManaV2ExtranetNatTranslationPeerToPeer(
                prefixes = [
                    graphiant_sdk.models.mana_v2_extranet_nat_translation_peer_to_peer_prefix.manaV2ExtranetNatTranslationPeerToPeerPrefix(
                        outside_nat_prefix = '100.1.2.0/24', 
                        prefix = '10.1.2.0/24', )
                    ]
            )
        else:
            return ManaV2ExtranetNatTranslationPeerToPeer(
        )
        """

    def testManaV2ExtranetNatTranslationPeerToPeer(self):
        """Test ManaV2ExtranetNatTranslationPeerToPeer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
