# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_extranet_nat_translation_device_prefixes import ManaV2ExtranetNatTranslationDevicePrefixes

class TestManaV2ExtranetNatTranslationDevicePrefixes(unittest.TestCase):
    """ManaV2ExtranetNatTranslationDevicePrefixes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2ExtranetNatTranslationDevicePrefixes:
        """Test ManaV2ExtranetNatTranslationDevicePrefixes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2ExtranetNatTranslationDevicePrefixes`
        """
        model = ManaV2ExtranetNatTranslationDevicePrefixes()
        if include_optional:
            return ManaV2ExtranetNatTranslationDevicePrefixes(
                prefixes = [
                    'example string'
                    ]
            )
        else:
            return ManaV2ExtranetNatTranslationDevicePrefixes(
        )
        """

    def testManaV2ExtranetNatTranslationDevicePrefixes(self):
        """Test ManaV2ExtranetNatTranslationDevicePrefixes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
