# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranet_b2b_matches_match_id_details_get_response import V1ExtranetB2bMatchesMatchIdDetailsGetResponse

class TestV1ExtranetB2bMatchesMatchIdDetailsGetResponse(unittest.TestCase):
    """V1ExtranetB2bMatchesMatchIdDetailsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetB2bMatchesMatchIdDetailsGetResponse:
        """Test V1ExtranetB2bMatchesMatchIdDetailsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetB2bMatchesMatchIdDetailsGetResponse`
        """
        model = V1ExtranetB2bMatchesMatchIdDetailsGetResponse()
        if include_optional:
            return V1ExtranetB2bMatchesMatchIdDetailsGetResponse(
                details = [
                    graphiant_sdk.models.mana_v2_b2b_extranet_match_consumer_details.manaV2B2bExtranetMatchConsumerDetails(
                        consumer_id = 1234567891011, 
                        consumer_prefixes = [
                            'example string'
                            ], 
                        customer = graphiant_sdk.models.mana_v2_b2_b_extranet_match_consumer_details_customer.manaV2B2BExtranetMatchConsumerDetailsCustomer(
                            admin_emails = [
                                'example string'
                                ], 
                            company_name = 'example string', 
                            id = 1234567891011, 
                            num_sites = 123, ), 
                        old_consumer_prefixes = [
                            'example string'
                            ], 
                        old_service_prefixes = [
                            graphiant_sdk.models.mana_v2_b2_b_extranet_match_consumer_details_producer_prefix.manaV2B2BExtranetMatchConsumerDetailsProducerPrefix(
                                customer_translated_prefix = 'example string', 
                                prefix = 'example string', 
                                tag = 'example string', )
                            ], 
                        service = graphiant_sdk.models.mana_v2_b2_b_extranet_match_consumer_details_service.manaV2B2BExtranetMatchConsumerDetailsService(
                            company_name = 'example string', 
                            contact_email = [
                                'example string'
                                ], 
                            description = 'example string', 
                            id = 1234567891011, 
                            service_name = 'example string', ), 
                        service_prefixes = [
                            graphiant_sdk.models.mana_v2_b2_b_extranet_match_consumer_details_producer_prefix.manaV2B2BExtranetMatchConsumerDetailsProducerPrefix(
                                customer_translated_prefix = 'example string', 
                                prefix = 'example string', 
                                tag = 'example string', )
                            ], )
                    ]
            )
        else:
            return V1ExtranetB2bMatchesMatchIdDetailsGetResponse(
        )
        """

    def testV1ExtranetB2bMatchesMatchIdDetailsGetResponse(self):
        """Test V1ExtranetB2bMatchesMatchIdDetailsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
