# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranet_b2b_matches_match_id_status_put_request import V1ExtranetB2bMatchesMatchIdStatusPutRequest

class TestV1ExtranetB2bMatchesMatchIdStatusPutRequest(unittest.TestCase):
    """V1ExtranetB2bMatchesMatchIdStatusPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetB2bMatchesMatchIdStatusPutRequest:
        """Test V1ExtranetB2bMatchesMatchIdStatusPutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetB2bMatchesMatchIdStatusPutRequest`
        """
        model = V1ExtranetB2bMatchesMatchIdStatusPutRequest()
        if include_optional:
            return V1ExtranetB2bMatchesMatchIdStatusPutRequest(
                status = 'ENUM_VALUE'
            )
        else:
            return V1ExtranetB2bMatchesMatchIdStatusPutRequest(
        )
        """

    def testV1ExtranetB2bMatchesMatchIdStatusPutRequest(self):
        """Test V1ExtranetB2bMatchesMatchIdStatusPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
