# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranet_b2b_customers_summary_get_response import V1ExtranetB2bCustomersSummaryGetResponse

class TestV1ExtranetB2bCustomersSummaryGetResponse(unittest.TestCase):
    """V1ExtranetB2bCustomersSummaryGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetB2bCustomersSummaryGetResponse:
        """Test V1ExtranetB2bCustomersSummaryGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetB2bCustomersSummaryGetResponse`
        """
        model = V1ExtranetB2bCustomersSummaryGetResponse()
        if include_optional:
            return V1ExtranetB2bCustomersSummaryGetResponse(
                customers = [
                    graphiant_sdk.models.mana_v2_extranet_service_customer_summary.manaV2ExtranetServiceCustomerSummary(
                        admin_emails = [
                            'example string'
                            ], 
                        id = 1234567891011, 
                        matched_services = 123, 
                        name = 'example string', 
                        status = 'ENUM_VALUE', 
                        type = 'ENUM_VALUE', 
                        updated_at = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), )
                    ]
            )
        else:
            return V1ExtranetB2bCustomersSummaryGetResponse(
        )
        """

    def testV1ExtranetB2bCustomersSummaryGetResponse(self):
        """Test V1ExtranetB2bCustomersSummaryGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
