# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_b2b_extranet_match_consumer_details import ManaV2B2bExtranetMatchConsumerDetails

class TestManaV2B2bExtranetMatchConsumerDetails(unittest.TestCase):
    """ManaV2B2bExtranetMatchConsumerDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2B2bExtranetMatchConsumerDetails:
        """Test ManaV2B2bExtranetMatchConsumerDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2B2bExtranetMatchConsumerDetails`
        """
        model = ManaV2B2bExtranetMatchConsumerDetails()
        if include_optional:
            return ManaV2B2bExtranetMatchConsumerDetails(
                consumer_id = 1234567891011,
                consumer_prefixes = [
                    'example string'
                    ],
                customer = graphiant_sdk.models.mana_v2_b2_b_extranet_match_consumer_details_customer.manaV2B2BExtranetMatchConsumerDetailsCustomer(
                    admin_emails = [
                        'example string'
                        ], 
                    company_name = 'example string', 
                    id = 1234567891011, 
                    num_sites = 123, ),
                old_consumer_prefixes = [
                    'example string'
                    ],
                old_service_prefixes = [
                    graphiant_sdk.models.mana_v2_b2_b_extranet_match_consumer_details_producer_prefix.manaV2B2BExtranetMatchConsumerDetailsProducerPrefix(
                        customer_translated_prefix = 'example string', 
                        prefix = 'example string', 
                        tag = 'example string', )
                    ],
                service = graphiant_sdk.models.mana_v2_b2_b_extranet_match_consumer_details_service.manaV2B2BExtranetMatchConsumerDetailsService(
                    company_name = 'example string', 
                    contact_email = [
                        'example string'
                        ], 
                    description = 'example string', 
                    id = 1234567891011, 
                    service_name = 'example string', ),
                service_prefixes = [
                    graphiant_sdk.models.mana_v2_b2_b_extranet_match_consumer_details_producer_prefix.manaV2B2BExtranetMatchConsumerDetailsProducerPrefix(
                        customer_translated_prefix = 'example string', 
                        prefix = 'example string', 
                        tag = 'example string', )
                    ]
            )
        else:
            return ManaV2B2bExtranetMatchConsumerDetails(
        )
        """

    def testManaV2B2bExtranetMatchConsumerDetails(self):
        """Test ManaV2B2bExtranetMatchConsumerDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
