# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_extranet_service_summary import ManaV2ExtranetServiceSummary

class TestManaV2ExtranetServiceSummary(unittest.TestCase):
    """ManaV2ExtranetServiceSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2ExtranetServiceSummary:
        """Test ManaV2ExtranetServiceSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2ExtranetServiceSummary`
        """
        model = ManaV2ExtranetServiceSummary()
        if include_optional:
            return ManaV2ExtranetServiceSummary(
                created_at = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, ),
                id = 1234567891011,
                is_publisher = True,
                lan_segment = 1234567891011,
                last_updated = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, ),
                server_prefixes = [
                    'example string'
                    ],
                service_name = 'example string',
                service_type = 'ENUM_VALUE',
                sites = [
                    1234567891011
                    ],
                status = 'ENUM_VALUE',
                total_customers = 123
            )
        else:
            return ManaV2ExtranetServiceSummary(
        )
        """

    def testManaV2ExtranetServiceSummary(self):
        """Test ManaV2ExtranetServiceSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
