# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_adaptive_fec_configuration import ManaV2AdaptiveFecConfiguration

class TestManaV2AdaptiveFecConfiguration(unittest.TestCase):
    """ManaV2AdaptiveFecConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2AdaptiveFecConfiguration:
        """Test ManaV2AdaptiveFecConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2AdaptiveFecConfiguration`
        """
        model = ManaV2AdaptiveFecConfiguration()
        if include_optional:
            return ManaV2AdaptiveFecConfiguration(
                adaptive_fec_enabled = True,
                sla_classes = [
                    'ENUM_VALUE'
                    ]
            )
        else:
            return ManaV2AdaptiveFecConfiguration(
        )
        """

    def testManaV2AdaptiveFecConfiguration(self):
        """Test ManaV2AdaptiveFecConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
