# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranet_b2b_customers_id_delete_response import V1ExtranetB2bCustomersIdDeleteResponse

class TestV1ExtranetB2bCustomersIdDeleteResponse(unittest.TestCase):
    """V1ExtranetB2bCustomersIdDeleteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetB2bCustomersIdDeleteResponse:
        """Test V1ExtranetB2bCustomersIdDeleteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetB2bCustomersIdDeleteResponse`
        """
        model = V1ExtranetB2bCustomersIdDeleteResponse()
        if include_optional:
            return V1ExtranetB2bCustomersIdDeleteResponse(
                activity_id = 'example string',
                consumer_activity_id = 'example string'
            )
        else:
            return V1ExtranetB2bCustomersIdDeleteResponse(
        )
        """

    def testV1ExtranetB2bCustomersIdDeleteResponse(self):
        """Test V1ExtranetB2bCustomersIdDeleteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
