# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranet_b2b_consumers_id_prefixes_put_request import V1ExtranetB2bConsumersIdPrefixesPutRequest

class TestV1ExtranetB2bConsumersIdPrefixesPutRequest(unittest.TestCase):
    """V1ExtranetB2bConsumersIdPrefixesPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetB2bConsumersIdPrefixesPutRequest:
        """Test V1ExtranetB2bConsumersIdPrefixesPutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetB2bConsumersIdPrefixesPutRequest`
        """
        model = V1ExtranetB2bConsumersIdPrefixesPutRequest()
        if include_optional:
            return V1ExtranetB2bConsumersIdPrefixesPutRequest(
                nat_translation_mode = graphiant_sdk.models.mana_v2_extranet_nat_translation_mode.manaV2ExtranetNatTranslationMode(
                    centralized = graphiant_sdk.models.mana_v2_extranet_nat_translation_centralized.manaV2ExtranetNatTranslationCentralized(
                        prefixes = {
                            'key' : graphiant_sdk.models.mana_v2_extranet_nat_translation_device_prefixes.manaV2ExtranetNatTranslationDevicePrefixes()
                            }, ), 
                    decentralized = graphiant_sdk.models.mana_v2_extranet_nat_translation_decentralized.manaV2ExtranetNatTranslationDecentralized(), 
                    peer_to_peer = graphiant_sdk.models.mana_v2_extranet_nat_translation_peer_to_peer.manaV2ExtranetNatTranslationPeerToPeer(), )
            )
        else:
            return V1ExtranetB2bConsumersIdPrefixesPutRequest(
        )
        """

    def testV1ExtranetB2bConsumersIdPrefixesPutRequest(self):
        """Test V1ExtranetB2bConsumersIdPrefixesPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
