# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranet_b2b_producer_id_device_status_get_response import V1ExtranetB2bProducerIdDeviceStatusGetResponse

class TestV1ExtranetB2bProducerIdDeviceStatusGetResponse(unittest.TestCase):
    """V1ExtranetB2bProducerIdDeviceStatusGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetB2bProducerIdDeviceStatusGetResponse:
        """Test V1ExtranetB2bProducerIdDeviceStatusGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetB2bProducerIdDeviceStatusGetResponse`
        """
        model = V1ExtranetB2bProducerIdDeviceStatusGetResponse()
        if include_optional:
            return V1ExtranetB2bProducerIdDeviceStatusGetResponse(
                summary = [
                    graphiant_sdk.models.mana_v2_b2b_extranet_status_summary.manaV2B2bExtranetStatusSummary(
                        created_at = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), 
                        device_id = 1234567891011, 
                        device_status = 'ENUM_VALUE', 
                        location = 1234567891011, 
                        status = 'ENUM_VALUE', )
                    ]
            )
        else:
            return V1ExtranetB2bProducerIdDeviceStatusGetResponse(
        )
        """

    def testV1ExtranetB2bProducerIdDeviceStatusGetResponse(self):
        """Test V1ExtranetB2bProducerIdDeviceStatusGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
