# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_nullable_ospf_authentication_config import ManaV2NullableOspfAuthenticationConfig

class TestManaV2NullableOspfAuthenticationConfig(unittest.TestCase):
    """ManaV2NullableOspfAuthenticationConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2NullableOspfAuthenticationConfig:
        """Test ManaV2NullableOspfAuthenticationConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2NullableOspfAuthenticationConfig`
        """
        model = ManaV2NullableOspfAuthenticationConfig()
        if include_optional:
            return ManaV2NullableOspfAuthenticationConfig(
                authentication = None
            )
        else:
            return ManaV2NullableOspfAuthenticationConfig(
        )
        """

    def testManaV2NullableOspfAuthenticationConfig(self):
        """Test ManaV2NullableOspfAuthenticationConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
