# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_extranet_consumer_lan_prefixes import ManaV2ExtranetConsumerLanPrefixes

class TestManaV2ExtranetConsumerLanPrefixes(unittest.TestCase):
    """ManaV2ExtranetConsumerLanPrefixes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2ExtranetConsumerLanPrefixes:
        """Test ManaV2ExtranetConsumerLanPrefixes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2ExtranetConsumerLanPrefixes`
        """
        model = ManaV2ExtranetConsumerLanPrefixes()
        if include_optional:
            return ManaV2ExtranetConsumerLanPrefixes(
                consumer_prefixes = [
                    'example string'
                    ],
                service_prefix_dnat = {
                    'key' : 'example string'
                    }
            )
        else:
            return ManaV2ExtranetConsumerLanPrefixes(
        )
        """

    def testManaV2ExtranetConsumerLanPrefixes(self):
        """Test ManaV2ExtranetConsumerLanPrefixes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
