# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranet_b2b_consumers_customer_id_get_response_ipsec_vpn_tunnel_config import V1ExtranetB2bConsumersCustomerIdGetResponseIpsecVpnTunnelConfig

class TestV1ExtranetB2bConsumersCustomerIdGetResponseIpsecVpnTunnelConfig(unittest.TestCase):
    """V1ExtranetB2bConsumersCustomerIdGetResponseIpsecVpnTunnelConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetB2bConsumersCustomerIdGetResponseIpsecVpnTunnelConfig:
        """Test V1ExtranetB2bConsumersCustomerIdGetResponseIpsecVpnTunnelConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetB2bConsumersCustomerIdGetResponseIpsecVpnTunnelConfig`
        """
        model = V1ExtranetB2bConsumersCustomerIdGetResponseIpsecVpnTunnelConfig()
        if include_optional:
            return V1ExtranetB2bConsumersCustomerIdGetResponseIpsecVpnTunnelConfig(
                bgp_graphiant_asn = 123,
                bgp_local_asn = 123,
                bgp_neighbor_hold_time = 123,
                bgp_neighbor_ipv4 = 'example string',
                bgp_neighbor_ipv6 = 'example string',
                dpd_interval = 123,
                dpd_retries = 123,
                graphiant_destination_ip = 'example string',
                graphiant_ike_id = 'example string',
                graphiant_outer_tunnel_ip = 'example string',
                graphiant_tunnel_ip = 'example string',
                graphiant_tunnel_ipv6 = 'example string',
                ike_authentication_algorithm = 'example string',
                ike_authentication_method = 'example string',
                ike_dh_algorithm = 'example string',
                ike_encryption_algorithm = 'example string',
                ike_lifetime = 'example string',
                ike_preshared_key = 'example string',
                ike_version = 123,
                ipsec_authentication_algorithm = 'example string',
                ipsec_encryption_algorithm = 'example string',
                ipsec_extended_sequence_number = True,
                ipsec_lifetime = 'example string',
                ipsec_mode = 'example string',
                ipsec_pfs_algorithm = 'example string',
                ipsec_protocol = 'example string',
                local_ike_id = 'example string',
                local_outer_tunnel_ip = 'example string',
                local_tunnel_ip = 'example string',
                local_tunnel_ipv6 = 'example string',
                tcp_mss = 123,
                tunnel_mtu = 123
            )
        else:
            return V1ExtranetB2bConsumersCustomerIdGetResponseIpsecVpnTunnelConfig(
        )
        """

    def testV1ExtranetB2bConsumersCustomerIdGetResponseIpsecVpnTunnelConfig(self):
        """Test V1ExtranetB2bConsumersCustomerIdGetResponseIpsecVpnTunnelConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
