# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_extranet_nat_translation_mode import ManaV2ExtranetNatTranslationMode

class TestManaV2ExtranetNatTranslationMode(unittest.TestCase):
    """ManaV2ExtranetNatTranslationMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2ExtranetNatTranslationMode:
        """Test ManaV2ExtranetNatTranslationMode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2ExtranetNatTranslationMode`
        """
        model = ManaV2ExtranetNatTranslationMode()
        if include_optional:
            return ManaV2ExtranetNatTranslationMode(
                centralized = graphiant_sdk.models.mana_v2_extranet_nat_translation_centralized.manaV2ExtranetNatTranslationCentralized(
                    prefixes = {
                        'key' : graphiant_sdk.models.mana_v2_extranet_nat_translation_device_prefixes.manaV2ExtranetNatTranslationDevicePrefixes()
                        }, ),
                decentralized = graphiant_sdk.models.mana_v2_extranet_nat_translation_decentralized.manaV2ExtranetNatTranslationDecentralized(
                    prefixes = {
                        'key' : graphiant_sdk.models.mana_v2_extranet_nat_translation_device_prefixes.manaV2ExtranetNatTranslationDevicePrefixes()
                        }, ),
                peer_to_peer = graphiant_sdk.models.mana_v2_extranet_nat_translation_peer_to_peer.manaV2ExtranetNatTranslationPeerToPeer(
                    prefixes = [
                        graphiant_sdk.models.mana_v2_extranet_nat_translation_peer_to_peer_prefix.manaV2ExtranetNatTranslationPeerToPeerPrefix(
                            outside_nat_prefix = '100.1.2.0/24', 
                            prefix = '10.1.2.0/24', )
                        ], )
            )
        else:
            return ManaV2ExtranetNatTranslationMode(
        )
        """

    def testManaV2ExtranetNatTranslationMode(self):
        """Test ManaV2ExtranetNatTranslationMode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
