# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_extranet_service_customer_invite import ManaV2ExtranetServiceCustomerInvite

class TestManaV2ExtranetServiceCustomerInvite(unittest.TestCase):
    """ManaV2ExtranetServiceCustomerInvite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2ExtranetServiceCustomerInvite:
        """Test ManaV2ExtranetServiceCustomerInvite
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2ExtranetServiceCustomerInvite`
        """
        model = ManaV2ExtranetServiceCustomerInvite()
        if include_optional:
            return ManaV2ExtranetServiceCustomerInvite(
                admin_emails = [
                    'example string'
                    ],
                maximum_number_of_sites = 123
            )
        else:
            return ManaV2ExtranetServiceCustomerInvite(
        )
        """

    def testManaV2ExtranetServiceCustomerInvite(self):
        """Test ManaV2ExtranetServiceCustomerInvite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
