# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_b2_b_extranet_match_consumer_details_customer import ManaV2B2BExtranetMatchConsumerDetailsCustomer

class TestManaV2B2BExtranetMatchConsumerDetailsCustomer(unittest.TestCase):
    """ManaV2B2BExtranetMatchConsumerDetailsCustomer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2B2BExtranetMatchConsumerDetailsCustomer:
        """Test ManaV2B2BExtranetMatchConsumerDetailsCustomer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2B2BExtranetMatchConsumerDetailsCustomer`
        """
        model = ManaV2B2BExtranetMatchConsumerDetailsCustomer()
        if include_optional:
            return ManaV2B2BExtranetMatchConsumerDetailsCustomer(
                admin_emails = [
                    'example string'
                    ],
                company_name = 'example string',
                id = 1234567891011,
                num_sites = 123
            )
        else:
            return ManaV2B2BExtranetMatchConsumerDetailsCustomer(
        )
        """

    def testManaV2B2BExtranetMatchConsumerDetailsCustomer(self):
        """Test ManaV2B2BExtranetMatchConsumerDetailsCustomer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
