# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_adaptive_fec_put_request import V1AdaptiveFecPutRequest

class TestV1AdaptiveFecPutRequest(unittest.TestCase):
    """V1AdaptiveFecPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AdaptiveFecPutRequest:
        """Test V1AdaptiveFecPutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AdaptiveFecPutRequest`
        """
        model = V1AdaptiveFecPutRequest()
        if include_optional:
            return V1AdaptiveFecPutRequest(
                configuration = graphiant_sdk.models.mana_v2_adaptive_fec_configuration.manaV2AdaptiveFecConfiguration(
                    adaptive_fec_enabled = True, 
                    sla_classes = [
                        'ENUM_VALUE'
                        ], )
            )
        else:
            return V1AdaptiveFecPutRequest(
        )
        """

    def testV1AdaptiveFecPutRequest(self):
        """Test V1AdaptiveFecPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
