# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranet_b2b_matches_customers_post_request import V1ExtranetB2bMatchesCustomersPostRequest

class TestV1ExtranetB2bMatchesCustomersPostRequest(unittest.TestCase):
    """V1ExtranetB2bMatchesCustomersPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetB2bMatchesCustomersPostRequest:
        """Test V1ExtranetB2bMatchesCustomersPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetB2bMatchesCustomersPostRequest`
        """
        model = V1ExtranetB2bMatchesCustomersPostRequest()
        if include_optional:
            return V1ExtranetB2bMatchesCustomersPostRequest(
                customers = [
                    graphiant_sdk.models.mana_v2_extranet_service_producer_customer.manaV2ExtranetServiceProducerCustomer(
                        admin_emails = [
                            'example string'
                            ], 
                        customer_id = 'example string', 
                        match_id = 1234567891011, 
                        matched_services = 123, 
                        name = 'example string', 
                        status = 'ENUM_VALUE', 
                        type = 'ENUM_VALUE', 
                        updated_at = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), )
                    ],
                service_id = 1234567891011
            )
        else:
            return V1ExtranetB2bMatchesCustomersPostRequest(
        )
        """

    def testV1ExtranetB2bMatchesCustomersPostRequest(self):
        """Test V1ExtranetB2bMatchesCustomersPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
