# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranet_b2b_matches_review_post_response import V1ExtranetB2bMatchesReviewPostResponse

class TestV1ExtranetB2bMatchesReviewPostResponse(unittest.TestCase):
    """V1ExtranetB2bMatchesReviewPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetB2bMatchesReviewPostResponse:
        """Test V1ExtranetB2bMatchesReviewPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetB2bMatchesReviewPostResponse`
        """
        model = V1ExtranetB2bMatchesReviewPostResponse()
        if include_optional:
            return V1ExtranetB2bMatchesReviewPostResponse(
                match_id = 1234567891011,
                matches = [
                    graphiant_sdk.models.mana_v2_b2b_extranet_match.manaV2B2bExtranetMatch(
                        consumer_prefixes = [
                            'example string'
                            ], 
                        lan_segment = 1234567891011, 
                        nat_translation_mode = graphiant_sdk.models.mana_v2_extranet_nat_translation_mode.manaV2ExtranetNatTranslationMode(
                            centralized = graphiant_sdk.models.mana_v2_extranet_nat_translation_centralized.manaV2ExtranetNatTranslationCentralized(
                                prefixes = {
                                    'key' : graphiant_sdk.models.mana_v2_extranet_nat_translation_device_prefixes.manaV2ExtranetNatTranslationDevicePrefixes()
                                    }, ), 
                            decentralized = graphiant_sdk.models.mana_v2_extranet_nat_translation_decentralized.manaV2ExtranetNatTranslationDecentralized(), 
                            peer_to_peer = graphiant_sdk.models.mana_v2_extranet_nat_translation_peer_to_peer.manaV2ExtranetNatTranslationPeerToPeer(), ), 
                        num_customers = 123, 
                        service_id = 1234567891011, 
                        service_prefixes = [
                            graphiant_sdk.models.mana_v2_b2b_extranet_prefix_tag.manaV2B2bExtranetPrefixTag(
                                prefix = '10.1.2.0/24', 
                                tag = 'example string', )
                            ], )
                    ]
            )
        else:
            return V1ExtranetB2bMatchesReviewPostResponse(
        )
        """

    def testV1ExtranetB2bMatchesReviewPostResponse(self):
        """Test V1ExtranetB2bMatchesReviewPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
