# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_b2_b_extranet_match_consumer_details_producer_prefix import ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix

class TestManaV2B2BExtranetMatchConsumerDetailsProducerPrefix(unittest.TestCase):
    """ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix:
        """Test ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix`
        """
        model = ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix()
        if include_optional:
            return ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix(
                customer_translated_prefix = 'example string',
                prefix = 'example string',
                tag = 'example string'
            )
        else:
            return ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix(
        )
        """

    def testManaV2B2BExtranetMatchConsumerDetailsProducerPrefix(self):
        """Test ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
