# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**   1) Login using /api/v1/auth/login   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: \"Bearer &lt;paste token from login api response&gt;\"   5) Click \"Authorize\"   6) If a valid token was entered, all requests are now authorized    **The token is valid for 2 hours, if it's expired (403 response from apis):**  1) Login again using the login api  2) Click \"Authorize\"  3) Click \"Logout\" and enter the new token just as before  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Graphiant APIs",
    author_email="",
    url="",
    keywords=["Swagger", "Graphiant APIs"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    **To use the APIs:**   1) Login using /api/v1/auth/login   2) Copy the value of \&quot;token\&quot; in the response   3) Click the \&quot;Authorize\&quot; button   4) In the \&quot;Value\&quot; text field enter: \&quot;Bearer &amp;lt;paste token from login api response&amp;gt;\&quot;   5) Click \&quot;Authorize\&quot;   6) If a valid token was entered, all requests are now authorized    **The token is valid for 2 hours, if it&#x27;s expired (403 response from apis):**  1) Login again using the login api  2) Click \&quot;Authorize\&quot;  3) Click \&quot;Logout\&quot; and enter the new token just as before  # noqa: E501
    """
)
