# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**   1) Login using /api/v1/auth/login   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: \"Bearer &lt;paste token from login api response&gt;\"   5) Click \"Authorize\"   6) If a valid token was entered, all requests are now authorized    **The token is valid for 2 hours, if it's expired (403 response from apis):**  1) Login again using the login api  2) Click \"Authorize\"  3) Click \"Logout\" and enter the new token just as before  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200112TrafficRules(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'action': 'InlineResponse200112Action',
        'match': 'InlineResponse200112Match',
        'seq': 'str'
    }

    attribute_map = {
        'action': 'action',
        'match': 'match',
        'seq': 'seq'
    }

    def __init__(self, action=None, match=None, seq=None):  # noqa: E501
        """InlineResponse200112TrafficRules - a model defined in Swagger"""  # noqa: E501
        self._action = None
        self._match = None
        self._seq = None
        self.discriminator = None
        if action is not None:
            self.action = action
        if match is not None:
            self.match = match
        if seq is not None:
            self.seq = seq

    @property
    def action(self):
        """Gets the action of this InlineResponse200112TrafficRules.  # noqa: E501


        :return: The action of this InlineResponse200112TrafficRules.  # noqa: E501
        :rtype: InlineResponse200112Action
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this InlineResponse200112TrafficRules.


        :param action: The action of this InlineResponse200112TrafficRules.  # noqa: E501
        :type: InlineResponse200112Action
        """

        self._action = action

    @property
    def match(self):
        """Gets the match of this InlineResponse200112TrafficRules.  # noqa: E501


        :return: The match of this InlineResponse200112TrafficRules.  # noqa: E501
        :rtype: InlineResponse200112Match
        """
        return self._match

    @match.setter
    def match(self, match):
        """Sets the match of this InlineResponse200112TrafficRules.


        :param match: The match of this InlineResponse200112TrafficRules.  # noqa: E501
        :type: InlineResponse200112Match
        """

        self._match = match

    @property
    def seq(self):
        """Gets the seq of this InlineResponse200112TrafficRules.  # noqa: E501


        :return: The seq of this InlineResponse200112TrafficRules.  # noqa: E501
        :rtype: str
        """
        return self._seq

    @seq.setter
    def seq(self, seq):
        """Sets the seq of this InlineResponse200112TrafficRules.


        :param seq: The seq of this InlineResponse200112TrafficRules.  # noqa: E501
        :type: str
        """

        self._seq = seq

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200112TrafficRules, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200112TrafficRules):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
