# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**   1) Login using /api/v1/auth/login   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: \"Bearer &lt;paste token from login api response&gt;\"   5) Click \"Authorize\"   6) If a valid token was entered, all requests are now authorized    **The token is valid for 2 hours, if it's expired (403 response from apis):**  1) Login again using the login api  2) Click \"Authorize\"  3) Click \"Logout\" and enter the new token just as before  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20096Responses(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'admin_email': 'str',
        'consumer_bw_site': 'str',
        'enterprise_id': 'str',
        'id': 'str',
        'maximum_site_count': 'str'
    }

    attribute_map = {
        'admin_email': 'adminEmail',
        'consumer_bw_site': 'consumerBwSite',
        'enterprise_id': 'enterpriseId',
        'id': 'id',
        'maximum_site_count': 'maximumSiteCount'
    }

    def __init__(self, admin_email=None, consumer_bw_site=None, enterprise_id=None, id=None, maximum_site_count=None):  # noqa: E501
        """InlineResponse20096Responses - a model defined in Swagger"""  # noqa: E501
        self._admin_email = None
        self._consumer_bw_site = None
        self._enterprise_id = None
        self._id = None
        self._maximum_site_count = None
        self.discriminator = None
        if admin_email is not None:
            self.admin_email = admin_email
        if consumer_bw_site is not None:
            self.consumer_bw_site = consumer_bw_site
        if enterprise_id is not None:
            self.enterprise_id = enterprise_id
        if id is not None:
            self.id = id
        if maximum_site_count is not None:
            self.maximum_site_count = maximum_site_count

    @property
    def admin_email(self):
        """Gets the admin_email of this InlineResponse20096Responses.  # noqa: E501


        :return: The admin_email of this InlineResponse20096Responses.  # noqa: E501
        :rtype: str
        """
        return self._admin_email

    @admin_email.setter
    def admin_email(self, admin_email):
        """Sets the admin_email of this InlineResponse20096Responses.


        :param admin_email: The admin_email of this InlineResponse20096Responses.  # noqa: E501
        :type: str
        """

        self._admin_email = admin_email

    @property
    def consumer_bw_site(self):
        """Gets the consumer_bw_site of this InlineResponse20096Responses.  # noqa: E501


        :return: The consumer_bw_site of this InlineResponse20096Responses.  # noqa: E501
        :rtype: str
        """
        return self._consumer_bw_site

    @consumer_bw_site.setter
    def consumer_bw_site(self, consumer_bw_site):
        """Sets the consumer_bw_site of this InlineResponse20096Responses.


        :param consumer_bw_site: The consumer_bw_site of this InlineResponse20096Responses.  # noqa: E501
        :type: str
        """

        self._consumer_bw_site = consumer_bw_site

    @property
    def enterprise_id(self):
        """Gets the enterprise_id of this InlineResponse20096Responses.  # noqa: E501


        :return: The enterprise_id of this InlineResponse20096Responses.  # noqa: E501
        :rtype: str
        """
        return self._enterprise_id

    @enterprise_id.setter
    def enterprise_id(self, enterprise_id):
        """Sets the enterprise_id of this InlineResponse20096Responses.


        :param enterprise_id: The enterprise_id of this InlineResponse20096Responses.  # noqa: E501
        :type: str
        """

        self._enterprise_id = enterprise_id

    @property
    def id(self):
        """Gets the id of this InlineResponse20096Responses.  # noqa: E501


        :return: The id of this InlineResponse20096Responses.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20096Responses.


        :param id: The id of this InlineResponse20096Responses.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def maximum_site_count(self):
        """Gets the maximum_site_count of this InlineResponse20096Responses.  # noqa: E501


        :return: The maximum_site_count of this InlineResponse20096Responses.  # noqa: E501
        :rtype: str
        """
        return self._maximum_site_count

    @maximum_site_count.setter
    def maximum_site_count(self, maximum_site_count):
        """Sets the maximum_site_count of this InlineResponse20096Responses.


        :param maximum_site_count: The maximum_site_count of this InlineResponse20096Responses.  # noqa: E501
        :type: str
        """

        self._maximum_site_count = maximum_site_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20096Responses, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20096Responses):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
