# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**   1) Login using /api/v1/auth/login   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: \"Bearer &lt;paste token from login api response&gt;\"   5) Click \"Authorize\"   6) If a valid token was entered, all requests are now authorized    **The token is valid for 2 hours, if it's expired (403 response from apis):**  1) Login again using the login api  2) Click \"Authorize\"  3) Click \"Logout\" and enter the new token just as before  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20063Enterprises(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'accept_eula': 'str',
        'account_type': 'str',
        'admin_email': 'str',
        'company_name': 'str',
        'counts': 'InlineResponse20063Counts',
        'customers': 'list[InlineResponse20063Customers]',
        'enterprise_id': 'str',
        'eula_agreement_date': 'V1devicesbringuptokenValidTillTs',
        'impersonation_enabled': 'str',
        'parent_company_name': 'str',
        'parent_enterprise_id': 'str',
        'portal_banner': 'str'
    }

    attribute_map = {
        'accept_eula': 'acceptEula',
        'account_type': 'accountType',
        'admin_email': 'adminEmail',
        'company_name': 'companyName',
        'counts': 'counts',
        'customers': 'customers',
        'enterprise_id': 'enterpriseId',
        'eula_agreement_date': 'eulaAgreementDate',
        'impersonation_enabled': 'impersonationEnabled',
        'parent_company_name': 'parentCompanyName',
        'parent_enterprise_id': 'parentEnterpriseId',
        'portal_banner': 'portalBanner'
    }

    def __init__(self, accept_eula=None, account_type=None, admin_email=None, company_name=None, counts=None, customers=None, enterprise_id=None, eula_agreement_date=None, impersonation_enabled=None, parent_company_name=None, parent_enterprise_id=None, portal_banner=None):  # noqa: E501
        """InlineResponse20063Enterprises - a model defined in Swagger"""  # noqa: E501
        self._accept_eula = None
        self._account_type = None
        self._admin_email = None
        self._company_name = None
        self._counts = None
        self._customers = None
        self._enterprise_id = None
        self._eula_agreement_date = None
        self._impersonation_enabled = None
        self._parent_company_name = None
        self._parent_enterprise_id = None
        self._portal_banner = None
        self.discriminator = None
        if accept_eula is not None:
            self.accept_eula = accept_eula
        if account_type is not None:
            self.account_type = account_type
        if admin_email is not None:
            self.admin_email = admin_email
        if company_name is not None:
            self.company_name = company_name
        if counts is not None:
            self.counts = counts
        if customers is not None:
            self.customers = customers
        if enterprise_id is not None:
            self.enterprise_id = enterprise_id
        if eula_agreement_date is not None:
            self.eula_agreement_date = eula_agreement_date
        if impersonation_enabled is not None:
            self.impersonation_enabled = impersonation_enabled
        if parent_company_name is not None:
            self.parent_company_name = parent_company_name
        if parent_enterprise_id is not None:
            self.parent_enterprise_id = parent_enterprise_id
        if portal_banner is not None:
            self.portal_banner = portal_banner

    @property
    def accept_eula(self):
        """Gets the accept_eula of this InlineResponse20063Enterprises.  # noqa: E501


        :return: The accept_eula of this InlineResponse20063Enterprises.  # noqa: E501
        :rtype: str
        """
        return self._accept_eula

    @accept_eula.setter
    def accept_eula(self, accept_eula):
        """Sets the accept_eula of this InlineResponse20063Enterprises.


        :param accept_eula: The accept_eula of this InlineResponse20063Enterprises.  # noqa: E501
        :type: str
        """

        self._accept_eula = accept_eula

    @property
    def account_type(self):
        """Gets the account_type of this InlineResponse20063Enterprises.  # noqa: E501


        :return: The account_type of this InlineResponse20063Enterprises.  # noqa: E501
        :rtype: str
        """
        return self._account_type

    @account_type.setter
    def account_type(self, account_type):
        """Sets the account_type of this InlineResponse20063Enterprises.


        :param account_type: The account_type of this InlineResponse20063Enterprises.  # noqa: E501
        :type: str
        """

        self._account_type = account_type

    @property
    def admin_email(self):
        """Gets the admin_email of this InlineResponse20063Enterprises.  # noqa: E501


        :return: The admin_email of this InlineResponse20063Enterprises.  # noqa: E501
        :rtype: str
        """
        return self._admin_email

    @admin_email.setter
    def admin_email(self, admin_email):
        """Sets the admin_email of this InlineResponse20063Enterprises.


        :param admin_email: The admin_email of this InlineResponse20063Enterprises.  # noqa: E501
        :type: str
        """

        self._admin_email = admin_email

    @property
    def company_name(self):
        """Gets the company_name of this InlineResponse20063Enterprises.  # noqa: E501


        :return: The company_name of this InlineResponse20063Enterprises.  # noqa: E501
        :rtype: str
        """
        return self._company_name

    @company_name.setter
    def company_name(self, company_name):
        """Sets the company_name of this InlineResponse20063Enterprises.


        :param company_name: The company_name of this InlineResponse20063Enterprises.  # noqa: E501
        :type: str
        """

        self._company_name = company_name

    @property
    def counts(self):
        """Gets the counts of this InlineResponse20063Enterprises.  # noqa: E501


        :return: The counts of this InlineResponse20063Enterprises.  # noqa: E501
        :rtype: InlineResponse20063Counts
        """
        return self._counts

    @counts.setter
    def counts(self, counts):
        """Sets the counts of this InlineResponse20063Enterprises.


        :param counts: The counts of this InlineResponse20063Enterprises.  # noqa: E501
        :type: InlineResponse20063Counts
        """

        self._counts = counts

    @property
    def customers(self):
        """Gets the customers of this InlineResponse20063Enterprises.  # noqa: E501


        :return: The customers of this InlineResponse20063Enterprises.  # noqa: E501
        :rtype: list[InlineResponse20063Customers]
        """
        return self._customers

    @customers.setter
    def customers(self, customers):
        """Sets the customers of this InlineResponse20063Enterprises.


        :param customers: The customers of this InlineResponse20063Enterprises.  # noqa: E501
        :type: list[InlineResponse20063Customers]
        """

        self._customers = customers

    @property
    def enterprise_id(self):
        """Gets the enterprise_id of this InlineResponse20063Enterprises.  # noqa: E501


        :return: The enterprise_id of this InlineResponse20063Enterprises.  # noqa: E501
        :rtype: str
        """
        return self._enterprise_id

    @enterprise_id.setter
    def enterprise_id(self, enterprise_id):
        """Sets the enterprise_id of this InlineResponse20063Enterprises.


        :param enterprise_id: The enterprise_id of this InlineResponse20063Enterprises.  # noqa: E501
        :type: str
        """

        self._enterprise_id = enterprise_id

    @property
    def eula_agreement_date(self):
        """Gets the eula_agreement_date of this InlineResponse20063Enterprises.  # noqa: E501


        :return: The eula_agreement_date of this InlineResponse20063Enterprises.  # noqa: E501
        :rtype: V1devicesbringuptokenValidTillTs
        """
        return self._eula_agreement_date

    @eula_agreement_date.setter
    def eula_agreement_date(self, eula_agreement_date):
        """Sets the eula_agreement_date of this InlineResponse20063Enterprises.


        :param eula_agreement_date: The eula_agreement_date of this InlineResponse20063Enterprises.  # noqa: E501
        :type: V1devicesbringuptokenValidTillTs
        """

        self._eula_agreement_date = eula_agreement_date

    @property
    def impersonation_enabled(self):
        """Gets the impersonation_enabled of this InlineResponse20063Enterprises.  # noqa: E501


        :return: The impersonation_enabled of this InlineResponse20063Enterprises.  # noqa: E501
        :rtype: str
        """
        return self._impersonation_enabled

    @impersonation_enabled.setter
    def impersonation_enabled(self, impersonation_enabled):
        """Sets the impersonation_enabled of this InlineResponse20063Enterprises.


        :param impersonation_enabled: The impersonation_enabled of this InlineResponse20063Enterprises.  # noqa: E501
        :type: str
        """

        self._impersonation_enabled = impersonation_enabled

    @property
    def parent_company_name(self):
        """Gets the parent_company_name of this InlineResponse20063Enterprises.  # noqa: E501


        :return: The parent_company_name of this InlineResponse20063Enterprises.  # noqa: E501
        :rtype: str
        """
        return self._parent_company_name

    @parent_company_name.setter
    def parent_company_name(self, parent_company_name):
        """Sets the parent_company_name of this InlineResponse20063Enterprises.


        :param parent_company_name: The parent_company_name of this InlineResponse20063Enterprises.  # noqa: E501
        :type: str
        """

        self._parent_company_name = parent_company_name

    @property
    def parent_enterprise_id(self):
        """Gets the parent_enterprise_id of this InlineResponse20063Enterprises.  # noqa: E501


        :return: The parent_enterprise_id of this InlineResponse20063Enterprises.  # noqa: E501
        :rtype: str
        """
        return self._parent_enterprise_id

    @parent_enterprise_id.setter
    def parent_enterprise_id(self, parent_enterprise_id):
        """Sets the parent_enterprise_id of this InlineResponse20063Enterprises.


        :param parent_enterprise_id: The parent_enterprise_id of this InlineResponse20063Enterprises.  # noqa: E501
        :type: str
        """

        self._parent_enterprise_id = parent_enterprise_id

    @property
    def portal_banner(self):
        """Gets the portal_banner of this InlineResponse20063Enterprises.  # noqa: E501


        :return: The portal_banner of this InlineResponse20063Enterprises.  # noqa: E501
        :rtype: str
        """
        return self._portal_banner

    @portal_banner.setter
    def portal_banner(self, portal_banner):
        """Sets the portal_banner of this InlineResponse20063Enterprises.


        :param portal_banner: The portal_banner of this InlineResponse20063Enterprises.  # noqa: E501
        :type: str
        """

        self._portal_banner = portal_banner

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20063Enterprises, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20063Enterprises):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
