# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**   1) Login using /api/v1/auth/login   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: \"Bearer &lt;paste token from login api response&gt;\"   5) Click \"Authorize\"   6) If a valid token was entered, all requests are now authorized    **The token is valid for 2 hours, if it's expired (403 response from apis):**  1) Login again using the login api  2) Click \"Authorize\"  3) Click \"Logout\" and enter the new token just as before  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1EnterprisesBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_type': 'str',
        'admin_email': 'str',
        'admin_first_name': 'str',
        'admin_last_name': 'str',
        'admin_time_zone': 'str',
        'company_name': 'str'
    }

    attribute_map = {
        'account_type': 'accountType',
        'admin_email': 'adminEmail',
        'admin_first_name': 'adminFirstName',
        'admin_last_name': 'adminLastName',
        'admin_time_zone': 'adminTimeZone',
        'company_name': 'companyName'
    }

    def __init__(self, account_type=None, admin_email=None, admin_first_name=None, admin_last_name=None, admin_time_zone=None, company_name=None):  # noqa: E501
        """V1EnterprisesBody - a model defined in Swagger"""  # noqa: E501
        self._account_type = None
        self._admin_email = None
        self._admin_first_name = None
        self._admin_last_name = None
        self._admin_time_zone = None
        self._company_name = None
        self.discriminator = None
        if account_type is not None:
            self.account_type = account_type
        if admin_email is not None:
            self.admin_email = admin_email
        if admin_first_name is not None:
            self.admin_first_name = admin_first_name
        if admin_last_name is not None:
            self.admin_last_name = admin_last_name
        if admin_time_zone is not None:
            self.admin_time_zone = admin_time_zone
        if company_name is not None:
            self.company_name = company_name

    @property
    def account_type(self):
        """Gets the account_type of this V1EnterprisesBody.  # noqa: E501


        :return: The account_type of this V1EnterprisesBody.  # noqa: E501
        :rtype: str
        """
        return self._account_type

    @account_type.setter
    def account_type(self, account_type):
        """Sets the account_type of this V1EnterprisesBody.


        :param account_type: The account_type of this V1EnterprisesBody.  # noqa: E501
        :type: str
        """

        self._account_type = account_type

    @property
    def admin_email(self):
        """Gets the admin_email of this V1EnterprisesBody.  # noqa: E501


        :return: The admin_email of this V1EnterprisesBody.  # noqa: E501
        :rtype: str
        """
        return self._admin_email

    @admin_email.setter
    def admin_email(self, admin_email):
        """Sets the admin_email of this V1EnterprisesBody.


        :param admin_email: The admin_email of this V1EnterprisesBody.  # noqa: E501
        :type: str
        """

        self._admin_email = admin_email

    @property
    def admin_first_name(self):
        """Gets the admin_first_name of this V1EnterprisesBody.  # noqa: E501


        :return: The admin_first_name of this V1EnterprisesBody.  # noqa: E501
        :rtype: str
        """
        return self._admin_first_name

    @admin_first_name.setter
    def admin_first_name(self, admin_first_name):
        """Sets the admin_first_name of this V1EnterprisesBody.


        :param admin_first_name: The admin_first_name of this V1EnterprisesBody.  # noqa: E501
        :type: str
        """

        self._admin_first_name = admin_first_name

    @property
    def admin_last_name(self):
        """Gets the admin_last_name of this V1EnterprisesBody.  # noqa: E501


        :return: The admin_last_name of this V1EnterprisesBody.  # noqa: E501
        :rtype: str
        """
        return self._admin_last_name

    @admin_last_name.setter
    def admin_last_name(self, admin_last_name):
        """Sets the admin_last_name of this V1EnterprisesBody.


        :param admin_last_name: The admin_last_name of this V1EnterprisesBody.  # noqa: E501
        :type: str
        """

        self._admin_last_name = admin_last_name

    @property
    def admin_time_zone(self):
        """Gets the admin_time_zone of this V1EnterprisesBody.  # noqa: E501


        :return: The admin_time_zone of this V1EnterprisesBody.  # noqa: E501
        :rtype: str
        """
        return self._admin_time_zone

    @admin_time_zone.setter
    def admin_time_zone(self, admin_time_zone):
        """Sets the admin_time_zone of this V1EnterprisesBody.


        :param admin_time_zone: The admin_time_zone of this V1EnterprisesBody.  # noqa: E501
        :type: str
        """

        self._admin_time_zone = admin_time_zone

    @property
    def company_name(self):
        """Gets the company_name of this V1EnterprisesBody.  # noqa: E501


        :return: The company_name of this V1EnterprisesBody.  # noqa: E501
        :rtype: str
        """
        return self._company_name

    @company_name.setter
    def company_name(self, company_name):
        """Sets the company_name of this V1EnterprisesBody.


        :param company_name: The company_name of this V1EnterprisesBody.  # noqa: E501
        :type: str
        """

        self._company_name = company_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1EnterprisesBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1EnterprisesBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
