# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**   1) Login using /api/v1/auth/login   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: \"Bearer &lt;paste token from login api response&gt;\"   5) Click \"Authorize\"   6) If a valid token was entered, all requests are now authorized    **The token is valid for 2 hours, if it's expired (403 response from apis):**  1) Login again using the login api  2) Click \"Authorize\"  3) Click \"Logout\" and enter the new token just as before  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1EnterprisesBody1(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'admin_email': 'str',
        'company_name': 'str',
        'enterprise_id': 'str',
        'impersonation_enabled': 'str',
        'portal_banner': 'str'
    }

    attribute_map = {
        'admin_email': 'adminEmail',
        'company_name': 'companyName',
        'enterprise_id': 'enterpriseId',
        'impersonation_enabled': 'impersonationEnabled',
        'portal_banner': 'portalBanner'
    }

    def __init__(self, admin_email=None, company_name=None, enterprise_id=None, impersonation_enabled=None, portal_banner=None):  # noqa: E501
        """V1EnterprisesBody1 - a model defined in Swagger"""  # noqa: E501
        self._admin_email = None
        self._company_name = None
        self._enterprise_id = None
        self._impersonation_enabled = None
        self._portal_banner = None
        self.discriminator = None
        if admin_email is not None:
            self.admin_email = admin_email
        if company_name is not None:
            self.company_name = company_name
        if enterprise_id is not None:
            self.enterprise_id = enterprise_id
        if impersonation_enabled is not None:
            self.impersonation_enabled = impersonation_enabled
        if portal_banner is not None:
            self.portal_banner = portal_banner

    @property
    def admin_email(self):
        """Gets the admin_email of this V1EnterprisesBody1.  # noqa: E501


        :return: The admin_email of this V1EnterprisesBody1.  # noqa: E501
        :rtype: str
        """
        return self._admin_email

    @admin_email.setter
    def admin_email(self, admin_email):
        """Sets the admin_email of this V1EnterprisesBody1.


        :param admin_email: The admin_email of this V1EnterprisesBody1.  # noqa: E501
        :type: str
        """

        self._admin_email = admin_email

    @property
    def company_name(self):
        """Gets the company_name of this V1EnterprisesBody1.  # noqa: E501


        :return: The company_name of this V1EnterprisesBody1.  # noqa: E501
        :rtype: str
        """
        return self._company_name

    @company_name.setter
    def company_name(self, company_name):
        """Sets the company_name of this V1EnterprisesBody1.


        :param company_name: The company_name of this V1EnterprisesBody1.  # noqa: E501
        :type: str
        """

        self._company_name = company_name

    @property
    def enterprise_id(self):
        """Gets the enterprise_id of this V1EnterprisesBody1.  # noqa: E501


        :return: The enterprise_id of this V1EnterprisesBody1.  # noqa: E501
        :rtype: str
        """
        return self._enterprise_id

    @enterprise_id.setter
    def enterprise_id(self, enterprise_id):
        """Sets the enterprise_id of this V1EnterprisesBody1.


        :param enterprise_id: The enterprise_id of this V1EnterprisesBody1.  # noqa: E501
        :type: str
        """

        self._enterprise_id = enterprise_id

    @property
    def impersonation_enabled(self):
        """Gets the impersonation_enabled of this V1EnterprisesBody1.  # noqa: E501


        :return: The impersonation_enabled of this V1EnterprisesBody1.  # noqa: E501
        :rtype: str
        """
        return self._impersonation_enabled

    @impersonation_enabled.setter
    def impersonation_enabled(self, impersonation_enabled):
        """Sets the impersonation_enabled of this V1EnterprisesBody1.


        :param impersonation_enabled: The impersonation_enabled of this V1EnterprisesBody1.  # noqa: E501
        :type: str
        """

        self._impersonation_enabled = impersonation_enabled

    @property
    def portal_banner(self):
        """Gets the portal_banner of this V1EnterprisesBody1.  # noqa: E501


        :return: The portal_banner of this V1EnterprisesBody1.  # noqa: E501
        :rtype: str
        """
        return self._portal_banner

    @portal_banner.setter
    def portal_banner(self, portal_banner):
        """Sets the portal_banner of this V1EnterprisesBody1.


        :param portal_banner: The portal_banner of this V1EnterprisesBody1.  # noqa: E501
        :type: str
        """

        self._portal_banner = portal_banner

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1EnterprisesBody1, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1EnterprisesBody1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
