# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**   1) Login using /api/v1/auth/login   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: \"Bearer &lt;paste token from login api response&gt;\"   5) Click \"Authorize\"   6) If a valid token was entered, all requests are now authorized    **The token is valid for 2 hours, if it's expired (403 response from apis):**  1) Login again using the login api  2) Click \"Authorize\"  3) Click \"Logout\" and enter the new token just as before  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response200247_logs import InlineResponse200247Logs  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse200247Logs(unittest.TestCase):
    """InlineResponse200247Logs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200247Logs(self):
        """Test InlineResponse200247Logs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response200247_logs.InlineResponse200247Logs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
