# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class AssuranceUserDefinition(BaseModel):
    """
    AssuranceUserDefinition
    """ # noqa: E501
    data_sent: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="tokens sent by the user (required)", alias="dataSent")
    managed: Optional[StrictBool] = Field(default=None, description="whether the user is managed (required)")
    sessions_day: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="daily sessions for the user (required)", alias="sessionsDay")
    tokens_usage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="token usage (required)", alias="tokensUsage")
    tokens_usage_days: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="token usage per day (required)", alias="tokensUsageDays")
    user: Optional[StrictStr] = Field(default=None, description="user identifier (required)")
    vrf: Optional[StrictStr] = Field(default=None, description="VRF associated with the user (required)")
    __properties: ClassVar[List[str]] = ["dataSent", "managed", "sessionsDay", "tokensUsage", "tokensUsageDays", "user", "vrf"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssuranceUserDefinition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssuranceUserDefinition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dataSent": obj.get("dataSent"),
            "managed": obj.get("managed"),
            "sessionsDay": obj.get("sessionsDay"),
            "tokensUsage": obj.get("tokensUsage"),
            "tokensUsageDays": obj.get("tokensUsageDays"),
            "user": obj.get("user"),
            "vrf": obj.get("vrf")
        })
        return _obj


