# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class AssuranceKpiMetric(BaseModel):
    """
    AssuranceKpiMetric
    """ # noqa: E501
    delta: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="delta value for the metric")
    name: Optional[StrictStr] = Field(default=None, description="name of the metric")
    percent: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="AI adoption percent for the metric")
    tag: Optional[StrictStr] = Field(default=None, description="AI adoption tag for the metric")
    token_usage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="AI adoption token usage value", alias="tokenUsage")
    value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="metric value (required)")
    __properties: ClassVar[List[str]] = ["delta", "name", "percent", "tag", "tokenUsage", "value"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssuranceKpiMetric from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssuranceKpiMetric from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "delta": obj.get("delta"),
            "name": obj.get("name"),
            "percent": obj.get("percent"),
            "tag": obj.get("tag"),
            "tokenUsage": obj.get("tokenUsage"),
            "value": obj.get("value")
        })
        return _obj


