# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.mana_v2_b2b_site_information import ManaV2B2bSiteInformation
from graphiant_sdk.models.mana_v2_extranet_consumer_lan_prefixes import ManaV2ExtranetConsumerLanPrefixes
from graphiant_sdk.models.mana_v2_extranet_nat_translation_mode import ManaV2ExtranetNatTranslationMode
from graphiant_sdk.models.mana_v2_global_object_service_ops import ManaV2GlobalObjectServiceOps
from graphiant_sdk.models.mana_v2_guest_consumer_site_to_site_vpn_config import ManaV2GuestConsumerSiteToSiteVpnConfig
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2ExtranetServiceConsumerPolicy(BaseModel):
    """
    ManaV2ExtranetServiceConsumerPolicy
    """ # noqa: E501
    consumer_lan_segments: Dict[str, ManaV2ExtranetConsumerLanPrefixes] = Field(alias="consumerLanSegments")
    global_object_ops: Optional[Dict[str, ManaV2GlobalObjectServiceOps]] = Field(default=None, alias="globalObjectOps")
    nat_translation_mode: Optional[ManaV2ExtranetNatTranslationMode] = Field(default=None, alias="natTranslationMode")
    site_to_site_vpn: Optional[ManaV2GuestConsumerSiteToSiteVpnConfig] = Field(default=None, alias="siteToSiteVpn")
    sites: Optional[List[ManaV2B2bSiteInformation]] = None
    __properties: ClassVar[List[str]] = ["consumerLanSegments", "globalObjectOps", "natTranslationMode", "siteToSiteVpn", "sites"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2ExtranetServiceConsumerPolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in consumer_lan_segments (dict)
        _field_dict = {}
        if self.consumer_lan_segments:
            for _key_consumer_lan_segments in self.consumer_lan_segments:
                if self.consumer_lan_segments[_key_consumer_lan_segments]:
                    _field_dict[_key_consumer_lan_segments] = self.consumer_lan_segments[_key_consumer_lan_segments].to_dict()
            _dict['consumerLanSegments'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in global_object_ops (dict)
        _field_dict = {}
        if self.global_object_ops:
            for _key_global_object_ops in self.global_object_ops:
                if self.global_object_ops[_key_global_object_ops]:
                    _field_dict[_key_global_object_ops] = self.global_object_ops[_key_global_object_ops].to_dict()
            _dict['globalObjectOps'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of nat_translation_mode
        if self.nat_translation_mode:
            _dict['natTranslationMode'] = self.nat_translation_mode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of site_to_site_vpn
        if self.site_to_site_vpn:
            _dict['siteToSiteVpn'] = self.site_to_site_vpn.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in sites (list)
        _items = []
        if self.sites:
            for _item_sites in self.sites:
                if _item_sites:
                    _items.append(_item_sites.to_dict())
            _dict['sites'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2ExtranetServiceConsumerPolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "consumerLanSegments": dict(
                (_k, ManaV2ExtranetConsumerLanPrefixes.from_dict(_v))
                for _k, _v in obj["consumerLanSegments"].items()
            )
            if obj.get("consumerLanSegments") is not None
            else None,
            "globalObjectOps": dict(
                (_k, ManaV2GlobalObjectServiceOps.from_dict(_v))
                for _k, _v in obj["globalObjectOps"].items()
            )
            if obj.get("globalObjectOps") is not None
            else None,
            "natTranslationMode": ManaV2ExtranetNatTranslationMode.from_dict(obj["natTranslationMode"]) if obj.get("natTranslationMode") is not None else None,
            "siteToSiteVpn": ManaV2GuestConsumerSiteToSiteVpnConfig.from_dict(obj["siteToSiteVpn"]) if obj.get("siteToSiteVpn") is not None else None,
            "sites": [ManaV2B2bSiteInformation.from_dict(_item) for _item in obj["sites"]] if obj.get("sites") is not None else None
        })
        return _obj


