# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.mana_v2_extranet_nat_translation_device_prefixes import ManaV2ExtranetNatTranslationDevicePrefixes
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2ExtranetNatTranslationDecentralized(BaseModel):
    """
    ManaV2ExtranetNatTranslationDecentralized
    """ # noqa: E501
    prefixes: Optional[Dict[str, ManaV2ExtranetNatTranslationDevicePrefixes]] = None
    __properties: ClassVar[List[str]] = ["prefixes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2ExtranetNatTranslationDecentralized from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in prefixes (dict)
        _field_dict = {}
        if self.prefixes:
            for _key_prefixes in self.prefixes:
                if self.prefixes[_key_prefixes]:
                    _field_dict[_key_prefixes] = self.prefixes[_key_prefixes].to_dict()
            _dict['prefixes'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2ExtranetNatTranslationDecentralized from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "prefixes": dict(
                (_k, ManaV2ExtranetNatTranslationDevicePrefixes.from_dict(_v))
                for _k, _v in obj["prefixes"].items()
            )
            if obj.get("prefixes") is not None
            else None
        })
        return _obj


