# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from graphiant_sdk.models.google_protobuf_timestamp import GoogleProtobufTimestamp
from typing import Optional, Set
from typing_extensions import Self

class ManaV2ExtranetServiceSummary(BaseModel):
    """
    ManaV2ExtranetServiceSummary
    """ # noqa: E501
    created_at: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="createdAt")
    id: Optional[StrictInt] = None
    is_publisher: Optional[StrictBool] = Field(default=None, description="True when this enterprise publishes the service; false when consuming a remote producer", alias="isPublisher")
    lan_segment: Optional[StrictInt] = Field(default=None, description="Service LAN segment when is_publisher and VRF exists", alias="lanSegment")
    last_updated: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="lastUpdated")
    server_prefixes: Optional[List[StrictStr]] = Field(default=None, alias="serverPrefixes")
    service_name: Optional[StrictStr] = Field(default=None, alias="serviceName")
    service_type: Optional[StrictStr] = Field(default=None, alias="serviceType")
    sites: Optional[List[StrictInt]] = None
    status: Optional[StrictStr] = None
    total_customers: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="totalCustomers")
    __properties: ClassVar[List[str]] = ["createdAt", "id", "isPublisher", "lanSegment", "lastUpdated", "serverPrefixes", "serviceName", "serviceType", "sites", "status", "totalCustomers"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2ExtranetServiceSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_at
        if self.created_at:
            _dict['createdAt'] = self.created_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of last_updated
        if self.last_updated:
            _dict['lastUpdated'] = self.last_updated.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2ExtranetServiceSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdAt": GoogleProtobufTimestamp.from_dict(obj["createdAt"]) if obj.get("createdAt") is not None else None,
            "id": obj.get("id"),
            "isPublisher": obj.get("isPublisher"),
            "lanSegment": obj.get("lanSegment"),
            "lastUpdated": GoogleProtobufTimestamp.from_dict(obj["lastUpdated"]) if obj.get("lastUpdated") is not None else None,
            "serverPrefixes": obj.get("serverPrefixes"),
            "serviceName": obj.get("serviceName"),
            "serviceType": obj.get("serviceType"),
            "sites": obj.get("sites"),
            "status": obj.get("status"),
            "totalCustomers": obj.get("totalCustomers")
        })
        return _obj


